### ISSUE TITLE
Iterative changes instead of all of them in 2.0 version?

### ISSUE THREAD

**Issue by dukebody** [wesm/pandas2-design#1]
Disclaimer: I'm not involved in pandas development so my opinion here is not very informed. Sorry about that. :-/

According to my (little) experience in software development, huge refactors and changes in a library are often more difficult to drive forward and expose a larger bug surface than small, incremental changes. Moreover, releasing new versions with incremental changes helps users to test new functionality/changes and allocate enough time to identify and report new bugs.

Could changes proposed in this document be broken into independent "modules" that can be worked on separately and incrementally? For example:

1. Removing unused/deprecated functionality.
2. Logical/physical storage decoupling.
3. Missing data consistency.
4. Enhaced string handling.

Even though (2) is probably required to be able to solve (3) and (4), we could get (2) done in a 2.0 release, then (3) in 2.1, (4) in 2.2... etc.

Does that sound reasonable or do you believe it is better to make a big release with all these changes in a row? Are these changes more coupled than I think?

**Comment by wesm** [comment]
Can you open this issue in pydata/pandas-design? Thank you
